stages:
  split:
    cmd: python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/raw/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  scale:
    cmd: python src/data/scale_data.py
    deps:
      - src/data/scale_data.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - models/scaler.pkl

  tune:
    cmd: python src/models/tune_model.py
    deps:
      - src/models/tune_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/model.pkl
    outs:
      - data/predictions.csv
      - metrics/scores.json
